### PR TITLE
Fp16 support

### PR DESCRIPTION
**Pull request by kaixuanliu**

### CODE REVIEW

**Comment by LiSu** [comment]
@kaixuanliu Hi Kaixuan, thanks for the PR. You nay noticed that a flag `use_fp16` was added to `IGBHeteroDataset`. With this flag being `True`,  the feature will be loaded in the FP16 format. In the process of partitioning and partitioning loading in distributed training, the feature will be in FP16 format if `use_fp16` is set to `True` at`line 35` in `partition.py`.  Thus the changes in `dist_dataset.py` and `partition/base.py` could be skipped, but we do need a  `use_fp16` in `build_partition_feature.py` to indicate which feature to laod.

**Comment by kaixuanliu** [comment]
Yes. I think your advice is better. Have updated the code per your suggestion, except 1 thing: we want to keep the change that if we partition the dataset using fp32 by mistake or due to historical reason, we still can load the partition using fp16 format. Do you think it is necessary? or we can just overpass it.

**Comment by LiSu** [comment]
> Yes. I think your advice is better. Have updated the code per your suggestion, except 1 thing: we want to keep the change that if we partition the dataset using fp32 by mistake or due to historical reason, we still can load the partition using fp16 format. Do you think it is necessary? or we can just overpass it.

If the partitioning is based on FP32,  loading the partition using FP16 will be quite time consuming and we would like to exclude this cost from the benchmarking.  Thus I suggest that we keep all the partitioning and conversion operations offline. If the `use_fp16` flag is set,  then the loader will take feature in FP16 inputs without any conversion.

**Comment by kaixuanliu** [comment]
> > Yes. I think your advice is better. Have updated the code per your suggestion, except 1 thing: we want to keep the change that if we partition the dataset using fp32 by mistake or due to historical reason, we still can load the partition using fp16 format. Do you think it is necessary? or we can just overpass it.
> 
> If the partitioning is based on FP32, loading the partition using FP16 will be quite time consuming and we would like to exclude this cost from the benchmarking. Thus I suggest that we keep all the partitioning and conversion operations offline. If the `use_fp16` flag is set, then the loader will take feature in FP16 inputs without any conversion.

OK. Just removed related code.

**Review by LiSu — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
